import type { TemplateDefinition } from './resumeTypes';

export const ALL_TEMPLATES: TemplateDefinition[] = [
  // ── MODERN ────────────────────────────────────────────────────
  { id: 'modern_navy',      name: 'Modern Navy',          category: 'Modern', layout: 'two_col_left',  rendererFamily: 'ModernSidebar',  defaultPaletteId: 'navy_white',    defaultFontId: 'inter',        atsScore: 98, pages: 1, isPopular: true,  description: 'Sleek two-column layout with navy sidebar, bold name banner and skill chips.', tags: ['modern','two-column','sidebar'] },
  { id: 'modern_emerald',   name: 'Modern Emerald',       category: 'Modern', layout: 'two_col_left',  rendererFamily: 'ModernSidebar',  defaultPaletteId: 'emerald_white', defaultFontId: 'outfit',       atsScore: 97, pages: 1, isNew: true,      description: 'Two-column emerald green design with clean typography and section dividers.', tags: ['modern','green'] },
  { id: 'modern_teal',      name: 'Modern Teal',          category: 'Modern', layout: 'two_col_left',  rendererFamily: 'ModernSidebar',  defaultPaletteId: 'teal_white',    defaultFontId: 'dm_sans',      atsScore: 97, pages: 1, description: 'Teal-accented sidebar with white body — fresh and contemporary look.', tags: ['modern','teal'] },
  { id: 'modern_right_navy',name: 'Modern Right Sidebar',  category: 'Modern', layout: 'two_col_right', rendererFamily: 'ModernSidebar',  defaultPaletteId: 'navy_white',    defaultFontId: 'inter',        atsScore: 96, pages: 1, description: 'Right-sidebar modern layout with experience on the left.', tags: ['modern','right-sidebar'] },
  { id: 'modern_purple',    name: 'Modern Purple',        category: 'Modern', layout: 'two_col_left',  rendererFamily: 'ModernSidebar',  defaultPaletteId: 'purple_white',  defaultFontId: 'outfit',       atsScore: 95, pages: 1, isNew: true, description: 'Bold purple sidebar with white body for a vibrant modern look.', tags: ['modern','purple'] },
  { id: 'modern_forest',    name: 'Modern Forest',        category: 'Modern', layout: 'two_col_left',  rendererFamily: 'ModernSidebar',  defaultPaletteId: 'forest_white',  defaultFontId: 'inter',        atsScore: 97, pages: 1, description: 'Forest green two-column layout — professional and nature-inspired.', tags: ['modern','green','forest'] },
  { id: 'modern_slate',     name: 'Modern Slate',         category: 'Modern', layout: 'two_col_left',  rendererFamily: 'ModernSidebar',  defaultPaletteId: 'slate_white',   defaultFontId: 'dm_sans',      atsScore: 98, pages: 1, isPopular: true, description: 'Slate grey sidebar — understated and highly professional.', tags: ['modern','slate','minimal'] },
  { id: 'modern_charcoal',  name: 'Modern Charcoal',      category: 'Modern', layout: 'two_col_left',  rendererFamily: 'ModernSidebar',  defaultPaletteId: 'charcoal_white',defaultFontId: 'inter',        atsScore: 98, pages: 1, description: 'Charcoal sidebar with white content area — timeless and versatile.', tags: ['modern','dark'] },

  // ── EXECUTIVE ─────────────────────────────────────────────────
  { id: 'exec_navy',        name: 'Executive Navy',       category: 'Executive', layout: 'top_header',  rendererFamily: 'ExecutiveHeader', defaultPaletteId: 'navy_white',    defaultFontId: 'playfair',     atsScore: 96, pages: 1, isPopular: true, description: 'Full-width navy header banner with Playfair Display serif — commanding executive presence.', tags: ['executive','header','serif'] },
  { id: 'exec_charcoal',    name: 'Executive Charcoal',   category: 'Executive', layout: 'top_header',  rendererFamily: 'ExecutiveHeader', defaultPaletteId: 'charcoal_white',defaultFontId: 'merriweather', atsScore: 96, pages: 1, description: 'Charcoal header with Merriweather serif body — classic C-level style.', tags: ['executive','serif'] },
  { id: 'exec_burgundy',    name: 'Executive Burgundy',   category: 'Executive', layout: 'top_header',  rendererFamily: 'ExecutiveHeader', defaultPaletteId: 'burgundy_white', defaultFontId: 'playfair',    atsScore: 95, pages: 1, isNew: true, description: 'Burgundy header — perfect for senior directors and VPs.', tags: ['executive','burgundy'] },
  { id: 'exec_forest',      name: 'Executive Forest',     category: 'Executive', layout: 'top_header',  rendererFamily: 'ExecutiveHeader', defaultPaletteId: 'forest_white',  defaultFontId: 'merriweather', atsScore: 95, pages: 1, description: 'Forest green executive header with traditional serif typography.', tags: ['executive','green'] },
  { id: 'exec_gold',        name: 'Executive Gold',       category: 'Executive', layout: 'two_col_left',rendererFamily: 'ExecutiveHeader', defaultPaletteId: 'gold_white',    defaultFontId: 'playfair',     atsScore: 94, pages: 1, isNew: true, description: 'Warm gold-brown executive design with serif typography.', tags: ['executive','gold','luxury'] },
  { id: 'exec_slate',       name: 'Executive Slate',      category: 'Executive', layout: 'top_header',  rendererFamily: 'ExecutiveHeader', defaultPaletteId: 'slate_white',   defaultFontId: 'outfit',       atsScore: 96, pages: 1, description: 'Clean slate header — modern executive aesthetic.', tags: ['executive','slate'] },
  { id: 'exec_royal',       name: 'Executive Royal Blue', category: 'Executive', layout: 'top_header',  rendererFamily: 'ExecutiveHeader', defaultPaletteId: 'royal_blue_white',defaultFontId: 'inter',      atsScore: 97, pages: 1, isPopular: true, description: 'Royal blue header with bold full-width name — strong executive first impression.', tags: ['executive','blue'] },
  { id: 'exec_two_col',     name: 'Executive Sidebar',    category: 'Executive', layout: 'two_col_right',rendererFamily: 'ExecutiveHeader',defaultPaletteId: 'navy_white',    defaultFontId: 'merriweather', atsScore: 94, pages: 1, description: 'Two-column executive layout with timeline experience section.', tags: ['executive','two-column'] },

  // ── ATS PROFESSIONAL ─────────────────────────────────────────
  { id: 'ats_classic',       name: 'ATS Classic',          category: 'ATS Professional', layout: 'one_col', rendererFamily: 'AtsClassic', defaultPaletteId: 'slate_white',  defaultFontId: 'inter',   atsScore: 100, pages: 1, isPopular: true, description: '100% ATS-safe single-column layout with no columns, tables or graphics.', tags: ['ats','one-column','safe'] },
  { id: 'ats_clean_navy',    name: 'ATS Clean Navy',       category: 'ATS Professional', layout: 'one_col', rendererFamily: 'AtsClassic', defaultPaletteId: 'navy_white',  defaultFontId: 'inter',   atsScore: 100, pages: 1, isPopular: true, description: 'Single-column with navy accent headings — fully ATS compliant.', tags: ['ats','one-column','navy'] },
  { id: 'ats_forest',        name: 'ATS Forest',           category: 'ATS Professional', layout: 'one_col', rendererFamily: 'AtsClassic', defaultPaletteId: 'forest_white',defaultFontId: 'dm_sans', atsScore: 100, pages: 1, description: 'Forest green heading accents on clean one-column ATS layout.', tags: ['ats','green'] },
  { id: 'ats_minimal',       name: 'ATS Minimal',          category: 'ATS Professional', layout: 'one_col', rendererFamily: 'AtsClassic', defaultPaletteId: 'charcoal_white',defaultFontId: 'inter', atsScore: 100, pages: 1, description: 'Pure minimalist ATS layout with zero color — maximum parser compatibility.', tags: ['ats','minimal'] },
  { id: 'ats_teal',          name: 'ATS Teal',             category: 'ATS Professional', layout: 'one_col', rendererFamily: 'AtsClassic', defaultPaletteId: 'teal_white',  defaultFontId: 'outfit',  atsScore: 99,  pages: 1, description: 'Teal heading accents on a single-column safe ATS layout.', tags: ['ats','teal'] },
  { id: 'ats_burgundy',      name: 'ATS Burgundy',         category: 'ATS Professional', layout: 'one_col', rendererFamily: 'AtsClassic', defaultPaletteId: 'burgundy_white',defaultFontId: 'inter', atsScore: 99,  pages: 1, description: 'Sophisticated burgundy accents on ATS-optimized layout.', tags: ['ats','burgundy'] },
  { id: 'ats_merri',         name: 'ATS Serif Classic',    category: 'ATS Professional', layout: 'one_col', rendererFamily: 'AtsClassic', defaultPaletteId: 'slate_white', defaultFontId: 'merriweather', atsScore: 99, pages: 1, description: 'Merriweather serif on classic one-column — traditional and ATS-safe.', tags: ['ats','serif'] },
  { id: 'ats_royal',         name: 'ATS Royal Blue',       category: 'ATS Professional', layout: 'one_col', rendererFamily: 'AtsClassic', defaultPaletteId: 'royal_blue_white',defaultFontId: 'inter', atsScore: 100, pages: 1, isNew: true, description: 'Royal blue accents on ATS-safe single-column structure.', tags: ['ats','blue'] },

  // ── MINIMAL / ELEGANT ─────────────────────────────────────────
  { id: 'minimal_line_slate',name: 'Minimal Line',         category: 'Minimal', layout: 'one_col',     rendererFamily: 'MinimalLine', defaultPaletteId: 'slate_white',   defaultFontId: 'inter',   atsScore: 98, pages: 1, isPopular: true, description: 'Ultra-clean single column with thin accent dividers — restrained and refined.', tags: ['minimal','lines','clean'] },
  { id: 'minimal_line_teal', name: 'Minimal Teal Lines',   category: 'Minimal', layout: 'one_col',     rendererFamily: 'MinimalLine', defaultPaletteId: 'teal_white',    defaultFontId: 'dm_sans', atsScore: 98, pages: 1, description: 'Teal divider lines on minimal one-column layout.', tags: ['minimal','teal'] },
  { id: 'elegant_playfair',  name: 'Elegant Serif',        category: 'Elegant', layout: 'one_col',     rendererFamily: 'MinimalLine', defaultPaletteId: 'charcoal_white',defaultFontId: 'playfair',atsScore: 97, pages: 1, isPopular: true, description: 'Playfair Display serif headings — refined and sophisticated.', tags: ['elegant','serif','classic'] },
  { id: 'elegant_burgundy',  name: 'Elegant Burgundy',     category: 'Elegant', layout: 'two_col_left',rendererFamily: 'MinimalLine', defaultPaletteId: 'burgundy_white', defaultFontId: 'merriweather', atsScore: 95, pages: 1, isNew: true, description: 'Burgundy two-column elegant layout with serif typography.', tags: ['elegant','burgundy','serif'] },
  { id: 'elegant_gold',      name: 'Elegant Gold',         category: 'Elegant', layout: 'two_col_left',rendererFamily: 'MinimalLine', defaultPaletteId: 'gold_white',    defaultFontId: 'playfair', atsScore: 94, pages: 1, description: 'Warm gold-brown elegant layout — ideal for senior professionals.', tags: ['elegant','gold','luxury'] },
  { id: 'minimal_outfit',    name: 'Minimal Outfit',       category: 'Minimal', layout: 'one_col',     rendererFamily: 'MinimalLine', defaultPaletteId: 'navy_white',    defaultFontId: 'outfit',  atsScore: 98, pages: 1, description: 'Outfit font on clean single column — modern minimal look.', tags: ['minimal','modern'] },
  { id: 'minimal_forest',    name: 'Minimal Forest',       category: 'Minimal', layout: 'one_col',     rendererFamily: 'MinimalLine', defaultPaletteId: 'forest_white',  defaultFontId: 'dm_sans', atsScore: 98, pages: 1, description: 'Forest green accents on a minimal clean layout.', tags: ['minimal','green'] },
  { id: 'minimal_purple',    name: 'Minimal Purple',       category: 'Minimal', layout: 'one_col',     rendererFamily: 'MinimalLine', defaultPaletteId: 'purple_white',  defaultFontId: 'inter',   atsScore: 97, pages: 1, isNew: true, description: 'Deep purple accent minimal layout for creative professionals.', tags: ['minimal','purple'] },

  // ── SOFTWARE ENGINEER ─────────────────────────────────────────
  { id: 'swe_navy',          name: 'SWE Navy Pro',         category: 'Software Engineer', layout: 'two_col_left', rendererFamily: 'SoftwareEng', defaultPaletteId: 'navy_white',    defaultFontId: 'inter',    atsScore: 99, pages: 1, isPopular: true, description: 'GitHub-style two-column layout with tech stack chips and project links.', tags: ['software','github','chips'] },
  { id: 'swe_slate',         name: 'SWE Slate',            category: 'Software Engineer', layout: 'two_col_left', rendererFamily: 'SoftwareEng', defaultPaletteId: 'slate_white',   defaultFontId: 'roboto_mono',atsScore: 99, pages: 1, description: 'Monospace font with slate sidebar — for engineers who appreciate code aesthetics.', tags: ['software','mono','developer'] },
  { id: 'swe_teal',          name: 'SWE Teal Stack',       category: 'Software Engineer', layout: 'two_col_left', rendererFamily: 'SoftwareEng', defaultPaletteId: 'teal_white',    defaultFontId: 'outfit',   atsScore: 98, pages: 1, isNew: true, description: 'Teal sidebar with tech stack chips and metrics-first bullet style.', tags: ['software','teal'] },
  { id: 'swe_one_col',       name: 'SWE Minimal',          category: 'Software Engineer', layout: 'one_col',      rendererFamily: 'SoftwareEng', defaultPaletteId: 'charcoal_white',defaultFontId: 'inter',    atsScore: 100,pages: 1, isPopular: true, description: 'One-column ATS-safe layout tailored for software engineer job applications.', tags: ['software','ats','one-column'] },
  { id: 'ai_engineer',       name: 'AI/ML Engineer',       category: 'AI Engineer',       layout: 'two_col_left', rendererFamily: 'SoftwareEng', defaultPaletteId: 'royal_blue_white',defaultFontId: 'inter', atsScore: 98, pages: 1, isNew: true, description: 'Purpose-built for AI engineers — LLM, ML, RAG, model metrics sections.', tags: ['ai','ml','llm','researcher'] },
  { id: 'ai_engineer_slate', name: 'AI Engineer Slate',    category: 'AI Engineer',       layout: 'two_col_left', rendererFamily: 'SoftwareEng', defaultPaletteId: 'slate_white',   defaultFontId: 'roboto_mono',atsScore: 99, pages: 1, description: 'Slate monospace layout for AI researchers and ML practitioners.', tags: ['ai','slate','mono'] },
  { id: 'data_scientist',    name: 'Data Scientist Pro',   category: 'Data Scientist',    layout: 'two_col_left', rendererFamily: 'SoftwareEng', defaultPaletteId: 'teal_white',    defaultFontId: 'inter',    atsScore: 97, pages: 1, isPopular: true, description: 'Analytics-focused layout with metrics, publications and tech stack chips.', tags: ['data','analytics','scientist'] },
  { id: 'swe_forest',        name: 'SWE Forest',           category: 'Software Engineer', layout: 'two_col_left', rendererFamily: 'SoftwareEng', defaultPaletteId: 'forest_white',  defaultFontId: 'outfit',   atsScore: 98, pages: 1, description: 'Forest green developer layout — full stack focus.', tags: ['software','green'] },

  // ── STUDENT / FRESHER ─────────────────────────────────────────
  { id: 'student_navy',      name: 'Student Navy',         category: 'Student', layout: 'one_col',     rendererFamily: 'StudentFresher', defaultPaletteId: 'navy_white',    defaultFontId: 'inter',   atsScore: 99, pages: 1, isPopular: true, description: 'Clean student layout emphasizing education, projects, and hackathons.', tags: ['student','education','entry-level'] },
  { id: 'student_teal',      name: 'Student Teal',         category: 'Student', layout: 'two_col_left',rendererFamily: 'StudentFresher', defaultPaletteId: 'teal_white',    defaultFontId: 'outfit',  atsScore: 98, pages: 1, isNew: true, description: 'Two-column student design with skills sidebar and project cards.', tags: ['student','teal'] },
  { id: 'fresher_royal',     name: 'Fresher Royal Blue',   category: 'Fresher', layout: 'one_col',     rendererFamily: 'StudentFresher', defaultPaletteId: 'royal_blue_white',defaultFontId: 'inter', atsScore: 99, pages: 1, description: 'Perfect for recent grads — highlights education and skills prominently.', tags: ['fresher','entry-level','grad'] },
  { id: 'fresher_emerald',   name: 'Fresher Emerald',      category: 'Fresher', layout: 'two_col_left',rendererFamily: 'StudentFresher', defaultPaletteId: 'emerald_white', defaultFontId: 'dm_sans', atsScore: 98, pages: 1, isNew: true, description: 'Emerald two-column fresher layout with highlighted education section.', tags: ['fresher','green'] },
  { id: 'student_minimal',   name: 'Student Minimal',      category: 'Student', layout: 'one_col',     rendererFamily: 'StudentFresher', defaultPaletteId: 'slate_white',   defaultFontId: 'inter',   atsScore: 100,pages: 1, description: 'Ultra-clean minimal student resume — ATS perfect.', tags: ['student','minimal','ats'] },
  { id: 'internship_navy',   name: 'Internship Seeker',    category: 'Student', layout: 'one_col',     rendererFamily: 'StudentFresher', defaultPaletteId: 'navy_white',    defaultFontId: 'outfit',  atsScore: 99, pages: 1, description: 'Internship-focused layout with skills and coursework emphasis.', tags: ['internship','student'] },
  { id: 'student_forest',    name: 'Student Forest',       category: 'Student', layout: 'two_col_left',rendererFamily: 'StudentFresher', defaultPaletteId: 'forest_white',  defaultFontId: 'inter',   atsScore: 98, pages: 1, description: 'Forest green student layout — fresh and energetic.', tags: ['student','green'] },
  { id: 'student_purple',    name: 'Student Creative',     category: 'Student', layout: 'two_col_left',rendererFamily: 'StudentFresher', defaultPaletteId: 'purple_white',  defaultFontId: 'outfit',  atsScore: 96, pages: 1, description: 'Creative student layout with sidebar skills and activity section.', tags: ['student','creative','purple'] },

  // ── CORPORATE / FINANCE ───────────────────────────────────────
  { id: 'corp_navy',         name: 'Corporate Navy',       category: 'Corporate', layout: 'two_col_left',rendererFamily: 'Corporate', defaultPaletteId: 'navy_white',    defaultFontId: 'inter',        atsScore: 98, pages: 1, isPopular: true, description: 'Formal corporate two-column layout with navy sidebar and dotted skill ratings.', tags: ['corporate','formal','navy'] },
  { id: 'corp_charcoal',     name: 'Corporate Charcoal',   category: 'Corporate', layout: 'two_col_left',rendererFamily: 'Corporate', defaultPaletteId: 'charcoal_white',defaultFontId: 'merriweather', atsScore: 97, pages: 1, description: 'Charcoal sidebar with serif body — classic corporate identity.', tags: ['corporate','charcoal','serif'] },
  { id: 'finance_navy',      name: 'Finance Pro',          category: 'Finance', layout: 'one_col',     rendererFamily: 'Corporate', defaultPaletteId: 'navy_white',    defaultFontId: 'merriweather', atsScore: 99, pages: 1, isNew: true, description: 'Finance-sector layout — conservative, ATS-safe, serif typography.', tags: ['finance','one-column','conservative'] },
  { id: 'finance_slate',     name: 'Finance Slate',        category: 'Finance', layout: 'one_col',     rendererFamily: 'Corporate', defaultPaletteId: 'slate_white',   defaultFontId: 'inter',        atsScore: 99, pages: 1, description: 'Slate accented finance-optimized one-column layout.', tags: ['finance','slate'] },
  { id: 'corp_forest',       name: 'Corporate Forest',     category: 'Corporate', layout: 'two_col_left',rendererFamily: 'Corporate', defaultPaletteId: 'forest_white',  defaultFontId: 'inter',        atsScore: 97, pages: 1, description: 'Forest green corporate two-column — professional and modern.', tags: ['corporate','green'] },
  { id: 'corp_burgundy',     name: 'Corporate Burgundy',   category: 'Corporate', layout: 'two_col_left',rendererFamily: 'Corporate', defaultPaletteId: 'burgundy_white', defaultFontId: 'inter',       atsScore: 96, pages: 1, isNew: true, description: 'Burgundy corporate sidebar — sophisticated and distinctive.', tags: ['corporate','burgundy'] },
  { id: 'corp_royal',        name: 'Corporate Royal',      category: 'Corporate', layout: 'two_col_left',rendererFamily: 'Corporate', defaultPaletteId: 'royal_blue_white',defaultFontId: 'inter',     atsScore: 97, pages: 1, description: 'Royal blue corporate layout — confident and professional.', tags: ['corporate','blue'] },
  { id: 'sales_teal',        name: 'Sales Pro',            category: 'Sales', layout: 'two_col_left',  rendererFamily: 'Corporate', defaultPaletteId: 'teal_white',    defaultFontId: 'outfit',       atsScore: 97, pages: 1, description: 'Metrics-focused sales resume layout with achievement highlights.', tags: ['sales','metrics','teal'] },

  // ── CREATIVE / PORTFOLIO ──────────────────────────────────────
  { id: 'creative_purple',   name: 'Creative Purple',      category: 'Creative', layout: 'two_col_left',rendererFamily: 'CreativeCard', defaultPaletteId: 'purple_white',  defaultFontId: 'outfit',  atsScore: 92, pages: 1, isPopular: true, description: 'Bold purple sidebar with project card showcase and skill progress bars.', tags: ['creative','purple','cards'] },
  { id: 'portfolio_teal',    name: 'Portfolio Teal',       category: 'Portfolio', layout: 'two_col_left',rendererFamily: 'CreativeCard', defaultPaletteId: 'teal_white',   defaultFontId: 'outfit',  atsScore: 91, pages: 1, isNew: true, description: 'Portfolio-style layout with large project cards and tech badges.', tags: ['portfolio','cards','creative'] },
  { id: 'uxui_purple',       name: 'UI/UX Designer',       category: 'UI/UX Designer', layout: 'two_col_left',rendererFamily: 'CreativeCard', defaultPaletteId: 'purple_white', defaultFontId: 'outfit',  atsScore: 90, pages: 1, isPopular: true, description: 'Portfolio-focused UI/UX layout with visual case study section.', tags: ['uxui','designer','portfolio'] },
  { id: 'uxui_teal',         name: 'UX Designer Teal',     category: 'UI/UX Designer', layout: 'two_col_left',rendererFamily: 'CreativeCard', defaultPaletteId: 'teal_white',  defaultFontId: 'dm_sans', atsScore: 90, pages: 1, description: 'Teal UI/UX design layout with portfolio link and tool chips.', tags: ['uxui','teal'] },
  { id: 'marketing_emerald', name: 'Marketing Pro',        category: 'Marketing', layout: 'two_col_left',rendererFamily: 'CreativeCard', defaultPaletteId: 'emerald_white',defaultFontId: 'outfit', atsScore: 93, pages: 1, isNew: true, description: 'Marketing layout with campaign metrics, brand logos and channel expertise.', tags: ['marketing','metrics'] },
  { id: 'creative_burgundy', name: 'Creative Burgundy',    category: 'Creative', layout: 'two_col_left',rendererFamily: 'CreativeCard', defaultPaletteId: 'burgundy_white',defaultFontId: 'outfit', atsScore: 91, pages: 1, description: 'Elegant burgundy creative layout with award highlights.', tags: ['creative','burgundy'] },
  { id: 'product_mgr',       name: 'Product Manager',      category: 'Product Manager', layout: 'two_col_left',rendererFamily: 'CreativeCard', defaultPaletteId: 'navy_white',  defaultFontId: 'inter',   atsScore: 95, pages: 1, isPopular: true, description: 'Product manager layout with roadmap metrics, OKR, and stakeholder sections.', tags: ['product','pm','metrics'] },
  { id: 'creative_forest',   name: 'Creative Forest',      category: 'Creative', layout: 'two_col_left',rendererFamily: 'CreativeCard', defaultPaletteId: 'forest_white', defaultFontId: 'outfit',  atsScore: 92, pages: 1, description: 'Forest green creative layout for designers and content creators.', tags: ['creative','green'] },

  // ── STARTUP ───────────────────────────────────────────────────
  { id: 'startup_royal',     name: 'Startup Royal Blue',   category: 'Startup', layout: 'two_col_left', rendererFamily: 'Startup', defaultPaletteId: 'royal_blue_white',defaultFontId: 'outfit',  atsScore: 96, pages: 1, isPopular: true, description: 'Dynamic startup layout with founder metrics, funding bullets and impact scores.', tags: ['startup','founder','metrics'] },
  { id: 'startup_teal',      name: 'Startup Teal',         category: 'Startup', layout: 'two_col_left', rendererFamily: 'Startup', defaultPaletteId: 'teal_white',    defaultFontId: 'outfit',  atsScore: 95, pages: 1, isNew: true, description: 'Teal startup layout with growth metrics and tech stack.', tags: ['startup','teal','growth'] },
  { id: 'startup_emerald',   name: 'Startup Emerald',      category: 'Startup', layout: 'two_col_left', rendererFamily: 'Startup', defaultPaletteId: 'emerald_white', defaultFontId: 'inter',   atsScore: 95, pages: 1, description: 'Emerald startup resume for founders and early-stage employees.', tags: ['startup','green'] },
  { id: 'startup_purple',    name: 'Startup Purple',       category: 'Startup', layout: 'two_col_left', rendererFamily: 'Startup', defaultPaletteId: 'purple_white',  defaultFontId: 'outfit',  atsScore: 94, pages: 1, description: 'Bold purple startup layout with impact-focused bullets.', tags: ['startup','purple'] },
  { id: 'startup_slate',     name: 'Startup Minimal',      category: 'Startup', layout: 'one_col',      rendererFamily: 'Startup', defaultPaletteId: 'slate_white',   defaultFontId: 'inter',   atsScore: 97, pages: 1, description: 'Minimal ATS-safe startup layout for lean applicants.', tags: ['startup','minimal','ats'] },
  { id: 'startup_navy',      name: 'Startup Navy',         category: 'Startup', layout: 'two_col_left', rendererFamily: 'Startup', defaultPaletteId: 'navy_white',    defaultFontId: 'inter',   atsScore: 96, pages: 1, description: 'Navy two-column startup resume for product and engineering leads.', tags: ['startup','navy'] },
  { id: 'startup_forest',    name: 'Startup Forest',       category: 'Startup', layout: 'two_col_left', rendererFamily: 'Startup', defaultPaletteId: 'forest_white',  defaultFontId: 'outfit',  atsScore: 95, pages: 1, isNew: true, description: 'Forest green startup layout with impact metrics.', tags: ['startup','green'] },
  { id: 'startup_burgundy',  name: 'Startup Bold',         category: 'Startup', layout: 'top_header',   rendererFamily: 'Startup', defaultPaletteId: 'burgundy_white', defaultFontId: 'inter',  atsScore: 94, pages: 1, description: 'Burgundy header startup layout — distinctive and memorable.', tags: ['startup','bold'] },

  // ── HEALTHCARE / ACADEMIC ─────────────────────────────────────
  { id: 'health_navy',       name: 'Healthcare Navy',      category: 'Healthcare', layout: 'one_col', rendererFamily: 'Elegant', defaultPaletteId: 'navy_white',    defaultFontId: 'inter',        atsScore: 99, pages: 1, isNew: true, description: 'Clean one-column healthcare layout with certifications and clinical highlights.', tags: ['healthcare','clinical','one-column'] },
  { id: 'health_teal',       name: 'Healthcare Teal',      category: 'Healthcare', layout: 'one_col', rendererFamily: 'Elegant', defaultPaletteId: 'teal_white',    defaultFontId: 'dm_sans',      atsScore: 99, pages: 1, isPopular: true, description: 'Teal one-column healthcare layout — clean and professional.', tags: ['healthcare','teal'] },
  { id: 'academic_serif',    name: 'Academic CV',          category: 'Academic', layout: 'one_col',  rendererFamily: 'Elegant', defaultPaletteId: 'charcoal_white',defaultFontId: 'merriweather', atsScore: 98, pages: 2, isNew: true, description: 'Two-page academic CV with publications, research, and teaching sections.', tags: ['academic','cv','publications','research'] },
  { id: 'academic_navy',     name: 'Academic Navy',        category: 'Academic', layout: 'one_col',  rendererFamily: 'Elegant', defaultPaletteId: 'navy_white',    defaultFontId: 'playfair',     atsScore: 97, pages: 2, description: 'Navy Playfair academic CV for PhD and research professionals.', tags: ['academic','phd','research'] },
  { id: 'health_forest',     name: 'Healthcare Forest',    category: 'Healthcare', layout: 'two_col_left',rendererFamily: 'Elegant', defaultPaletteId: 'forest_white', defaultFontId: 'inter',       atsScore: 98, pages: 1, description: 'Forest green two-column healthcare layout with credential sidebar.', tags: ['healthcare','green'] },
  { id: 'health_slate',      name: 'Healthcare Slate',     category: 'Healthcare', layout: 'one_col', rendererFamily: 'Elegant', defaultPaletteId: 'slate_white',   defaultFontId: 'inter',        atsScore: 99, pages: 1, description: 'Slate minimal healthcare layout — ultra-clean and ATS-safe.', tags: ['healthcare','minimal'] },
  { id: 'academic_forest',   name: 'Academic Forest',      category: 'Academic', layout: 'one_col',  rendererFamily: 'Elegant', defaultPaletteId: 'forest_white',  defaultFontId: 'merriweather', atsScore: 98, pages: 2, description: 'Forest green academic CV with research and publications.', tags: ['academic','green','research'] },
  { id: 'academic_teal',     name: 'Academic Teal',        category: 'Academic', layout: 'one_col',  rendererFamily: 'Elegant', defaultPaletteId: 'teal_white',    defaultFontId: 'dm_sans',      atsScore: 97, pages: 1, description: 'Teal academic layout for lecturers and postgrad researchers.', tags: ['academic','teal'] },
];

export const TEMPLATE_CATEGORIES = [
  'All',
  'Modern', 'Executive', 'ATS Professional', 'Minimal', 'Elegant',
  'Software Engineer', 'AI Engineer', 'Data Scientist',
  'Student', 'Fresher', 'Corporate', 'Finance',
  'Creative', 'UI/UX Designer', 'Marketing', 'Product Manager',
  'Startup', 'Healthcare', 'Academic', 'Sales', 'Portfolio',
] as const;

export type TemplateCategoryFilter = typeof TEMPLATE_CATEGORIES[number];
